#!/usr/bin/env bash

(cd /home/kyriakos/Documents/Code/000_cerberus_dev/githubRelease-cerberus/cerberus/Exec/local && make -j8 DIM=2 USE_EB=FALSE AMREX_PARTICLES=TRUE)

EXE=/home/kyriakos/Documents/Code/000_cerberus_dev/githubRelease-cerberus/cerberus/Exec/local/MFP.2d.gnu.MPI.PARTICLES.ex

INPUTS=TRMI.inputs

rm -r *chk* *plt*
rm -r mov

python make_particles_file.py

mpirun -n 8 ${EXE} ${INPUTS} 2>&1 | tee run_log.txt

#../visit.sh .

#python3 movie.py
